name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./Frontend
        run: |
          npm install
          npm run build

      - name: Copy latest files to AWS server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/premier-data-systems"

      - name: Install dependencies and Restart AWS Services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            PROJECT_DIR="/home/ubuntu/premier-data-systems"
            
            # ------------------------------------------
            # 1. Deploy Frontend
            # ------------------------------------------
            sudo mkdir -p /var/www/html/frontend
            sudo rm -rf /var/www/html/frontend/* || true
            sudo cp -r $PROJECT_DIR/Frontend/dist/* /var/www/html/frontend/

            # ------------------------------------------
            # 2. Deploy Backend
            # ------------------------------------------
            cd $PROJECT_DIR/backend
            source venv/bin/activate
            pip install -r requirements.txt
            pm2 restart backend

            # ------------------------------------------
            # 3. Deploy WhatsApp Server
            # ------------------------------------------
            cd $PROJECT_DIR/whatsapp-server
            npm install
            pm2 restart whatsapp
